version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.http.ssl.enabled=false 
      - ELASTIC_PASSWORD=pintoss
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.skip_remaining_syscall_checks=true
    ports:
      - "9200:9200"
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"  # Beats input
      - "5001:5000"  # TCP input
      - "9600:9600"  # Monitoring API
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
